"use client";

import { createBrowserClient } from "@supabase/ssr";

// Browser-side Supabase client. Anon key only, RLS-respecting, writes its
// session to cookies so middleware.ts and every server component can read
// the same session. Used only by the auth forms — dashboard data is fetched
// server-side through userClient().

export function browserClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
  );
}

/**
 * Recovery links generated by the admin API use the implicit URL-fragment
 * flow. Keep this client separate from the PKCE client used by login so it
 * can consume that temporary session before the password is updated.
 */
export function recoveryBrowserClient() {
  return createBrowserClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { auth: { flowType: "implicit" } },
  );
}
